### PR TITLE
handle startup crashes

### LINKED ISSUE #3: Error screen does not work if the app crashes very quickly after launching
The library relies on a service running in a different process to process and display the error screen. This means that if the application crashes immediately after start, the service might not get enough time to be prepared for accepting new messages.

Unfortunately it looks like there is no easy solution for this problem.

### PR DESCRIPTION
**Pull request by matejdro**
this fixes https://github.com/haroldadmin/WhatTheStack/issues/3

### CODE REVIEW

File: what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt [hunk 1]
```diff
@@ -20,15 +32,88 @@ import android.os.*
...
+            }
+
+            if (stopAfterWaitingForFile) {
+                stopSelf()
+            }
+            finishedWaitingForFile = true
+        }
+    }
+
+    private fun showCrashNotification(crashBundle: Bundle) {
```
Comment (fvito) [inline what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt:77]: What happens if we don't have notification permissions? Do we just silently fail?
Not sure what the best approach there would be, but I know leak canary can throw up a permission dialog, which I'm not a big fan of

**Comment by fvito** [comment]
Thank you for this fix

File: what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt (hunk 1 above)
Comment (matejdro) [reply what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt:77]: We can't throw up any dialogs or show the user anything, because we are considered "in background" (foreground app has already crashed and closed). And since these types of crashes happen on startup, app crashes immediately and we cannot show the user any other UI.

So when app starts crashing on startup, user must first go to the System settings, enable notifications for the app and then open the app again (to crash again to show the notification).

Do you think we should include the notification permission in the manifest just to be sure app add it?

it is a bit shitty workaround, but I don't see any other option. Any ideas are welcome.

Comment (fvito) [reply what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt:77]: I assume that if we don't have notification permission that the service crashes when trying to send the notification?

I think it would be better if we can try to avoid pulutting the log with crashes from the library, as they can hide the original stacktrace and make it hard to check the logs

What if we add a check if we can send notification and we cannot, print a warning/error to the log?

Comment (matejdro) [reply what-the-stack/src/main/java/com/haroldadmin/whatthestack/WhatTheStackService.kt:77]: I've checked and it does not crash if there is no notification permission. But you are right that warning would be a good idea. Added that.
